# Generated by Django 4.2.14 on 2024-07-16 05:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "name_en",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=255, null=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("brand", models.CharField(max_length=255, verbose_name="brand")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="logo"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this product is in boycott (True) or normal (False).",
                        verbose_name="status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
