# Generated by Django 4.2.14 on 2024-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
    ]
