# Generated by Django 5.1.5 on 2025-01-27 16:58

from django.db import migrations, models

import apps.product.models.product


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.product.models.product.product_image_upload_path,
                verbose_name="Image",
            ),
        ),
    ]
