# Generated by Django 4.2.14 on 2024-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url_en",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
        migrations.AddField(
            model_name="product",
            name="url_kg",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
        migrations.AddField(
            model_name="product",
            name="url_ru",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
    ]
