# Generated by Django 4.2.14 on 2024-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_description_en_product_description_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_ky",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_tr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
