# Generated by Django 4.2.14 on 2024-07-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_description_ky_product_description_tr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="description_tr",
        ),
    ]
