# Generated by Django 4.2.14 on 2024-08-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_url_en_product_url_kg_product_url_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="alternatives",
            field=models.ManyToManyField(
                blank=True, to="product.product", verbose_name="alternatives"
            ),
        ),
    ]
