# Generated by Django 4.2.14 on 2024-07-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("first_name", "last_name"),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
