services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - boycott_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres_db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: boycott_user
      POSTGRES_DB: boycott_db
      POSTGRES_PASSWORD: boycott_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boycott_network

volumes:
  postgres_data:

networks:
  boycott_network:
