# Generated by Django 5.1.7 on 2025-04-01 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("moderator", "Moderator")],
                default="moderator",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registered User",
            ),
        ),
    ]
