# Generated by Django 5.1.5 on 2025-04-05 06:40

from django.db import migrations, models

import apps.account.models.code


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="expires_at",
            field=models.DateTimeField(default=apps.account.models.code.get_default_expiration),
        ),
    ]
