name: Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Запуск каждый день в 12:00 UTC
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Отключаем авто-аутентификацию, чтобы использовать токен

      - name: Установка Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Запуск скрипта
        run: python auto_commit.py

      - name: Настройка Git и Push
        run: |
          git config --global user.name "KenArsen"
          git config --global user.email "kenzhegulov.kgz@gmail.com"
          git add .
          git commit -m "Авто-коммит $(date)" || exit 0  # Если нечего коммитить, просто выходим
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/KenArsen/boycott.git HEAD:main
